In [2]:
import numpy as np

### 1. Kreirati niz a od 3 elementa i matricu M dimenzija 2×3 čiji su elementi tipa float32. Ispisati oblik, veličinu, broj dimenzija i tip elemenata niza a, odnosno matrice M.

In [6]:
a = np.array([1,2,3])
M = np.array([[1,2,3], [4,5,6]], dtype='float32')

print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

print('\n')

print(M)
print(M.shape)
print(M.size)
print(M.ndim)
print(M.dtype)

[1 2 3]
(3,)
3
1
int64


[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
6
2
float32


### 2. Generisati nizove i matrice na sledeći način:

##### Niz a1 tako što se zadaju početna i krajnja tačka sa odgovarajućim korakom.
##### Niz a2 gde se zadaju početna i krajnja tačka i broj ekvidistantnih elemenata u datom intervalu.
##### Niz a3 koji se sastoji samo od nula.
##### Niz a4 dobijen uniformnom raspodelom.
##### Matricu M1 koja se sastoji samo od jedinica.
##### Jediničnu matricu M dimenzije 3.
##### Dijagonalnu matricu M3 na čijoj se glavnoj dijagonali nalaze redom brojevi 4, 3, 2 i 1.
##### Matricu M4 čiji su elementi dobijeni standardnom normalnom raspodelom.

In [9]:
a1 = np.arange(1,10,2)
a2 = np.linspace(1,3,21)
a3 = np.zeros(6)
a4 = np.random.uniform(2,5,5)

print('a1 =', a1)
print('a2 =', a2)
print('a3 =', a3)
print('a4 =', a4)

M1 = np.ones((2,3))
M2 = np.eye(3)
M3 = np.diag([4,3,2,1])
M4 = np.random.randn(4,3)

print('M1 =\n', M1)
print('M2 =\n', M2)
print('M3 =\n', M3)
print('M4 =\n', M4)

a1 = [1 3 5 7 9]
a2 = [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3. ]
a3 = [0. 0. 0. 0. 0. 0.]
a4 = [3.80309546 2.71085467 2.84095729 3.10993244 4.85547827]
M1 =
 [[1. 1. 1.]
 [1. 1. 1.]]
M2 =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
M3 =
 [[4 0 0 0]
 [0 3 0 0]
 [0 0 2 0]
 [0 0 0 1]]
M4 =
 [[-1.2857549  -1.24918801 -0.40242947]
 [-0.21176985 -0.07891799 -1.511032  ]
 [-0.22974568  0.06430512  0.85305524]
 [-1.51646625 -0.16947718  0.29928861]]


**3.** Date su matrice $M\_1$ i $M\_2$. Odrediti vrednosti sledećih matrica:

*   $M\_1 + M\_2$, gde operacija $+$ označava sabiranje po koordinatama;
*   $M\_1 \cdot M\_2$, gde operacija $\cdot$ označava sabiranje po koordinatama;
*   $M\_1 \times M\_2$, gde operacija $\times$ označava matrično množenje;
*   transponovanu matricu $M\_1^T$ matrice $M\_1$;
*   $\\sin (M\_1)$, gde se vrednost funkcije $\\sin x$ računa po koordinatama;
*   $\\exp (M\_2)$, gde se vrednost funkcije $e^x$ računa po koordinatama.

In [11]:
M1 = np.array([[1, 3, 5], [7, 9, 11], [13, 15, 17]])
M2 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])

print('M1 + M2 =\n', M1 + M2)
print('M1 * M2 =\n', M1 * M2)
print('M1 x M2 =\n', M1.dot(M2), '=\n', np.dot(M1, M2))
print('transpose(M1) =\n', M1.T, '=\n', M1.transpose())
print('sin(M1) =\n', np.sin(M1))
print('exp(M2) =\n', np.exp(M2))

M1 + M2 =
 [[ 3  7 11]
 [15 19 23]
 [27 31 35]]
M1 * M2 =
 [[  2  12  30]
 [ 56  90 132]
 [182 240 306]]
M1 x M2 =
 [[ 96 114 132]
 [240 294 348]
 [384 474 564]] =
 [[ 96 114 132]
 [240 294 348]
 [384 474 564]]
transpose(M1) =
 [[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]] =
 [[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]
sin(M1) =
 [[ 0.84147098  0.14112001 -0.95892427]
 [ 0.6569866   0.41211849 -0.99999021]
 [ 0.42016704  0.65028784 -0.96139749]]
exp(M2) =
 [[7.38905610e+00 5.45981500e+01 4.03428793e+02]
 [2.98095799e+03 2.20264658e+04 1.62754791e+05]
 [1.20260428e+06 8.88611052e+06 6.56599691e+07]]


**4.** Dati su nizovi $x = [1, 2, 3]$ i $y = [5, 6, 7]$.

*   Nadovezati ih po vertikali i po horizontali.
*   Odrediti njihov skalarni proizvod.
*   Odrediti maksimalni element niza _x_.
*   Odrediti minimalni element niza _y_.
*   Odrediti sve elemente niza _x_ koji su veći od 1.5.


In [17]:
x = np.array([1,2,3])
y = np.array([5,6,7])

print(np.vstack((x,y)))
print(np.hstack((x,y)))
print(np.sum(x*y))
print(np.max(x))
print(y.min())
print(x[x>1.5])

[[1 2 3]
 [5 6 7]]
[1 2 3 5 6 7]
38
3
5
[2 3]


**5.** Date su matrice $A=\begin{bmatrix}1&2&3\\\\4&5&6\end{bmatrix}$ i $B=\begin{bmatrix}1&2&3\\\\4&6&6\end{bmatrix}$.

*   Proveriti da li su matrice jednake.
*   Proveriti da li su matrice jednake po svakoj koordinati.
*   Izvršiti preraspodelu elemenata matrice _A_ tako da se dobije matrica $3 \times 2$.
*   Izvršiti sravnjivanje elemenata matrice _A_.
*   Odrediti sumu elemenata matrice _B_ koji su jednaki 6.


In [25]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2, 3], [4, 6, 6]])

print(np.array_equal(A,B))
print(A==B)
print(A.reshape((3,2)))
print(A.flatten())
print(np.sum(B[B==6]))

False
[[ True  True  True]
 [ True False  True]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
12



**6.** Za $M = \begin{bmatrix}1&2&3\\\\4&5&6\end{bmatrix}$ i $x = [10, 20, 30]$ izračunati vrednosti $2M$, $x-3$ i $M+x$.

In [26]:
M = np.array([[1, 2, 3], [4, 5, 6]])
x = np.array([10, 20, 30])

print(2*M)
print(x-3)
print(M+x)

[[ 2  4  6]
 [ 8 10 12]]
[ 7 17 27]
[[11 22 33]
 [14 25 36]]


In [27]:
M = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('Pojedinacni element:', M[1,2])
print('Prva vrsta:', M[1])
print('Nulta kolona:', M[:,0])
print('Svaki drugi element poslednje kolone:', M[::2, -1])
print('Elementi na pozicijama (1,2) i (1,3):', M[(1,1), (2,3)])

Pojedinacni element: 7
Prva vrsta: [5 6 7 8]
Nulta kolona: [1 5 9]
Svaki drugi element poslednje kolone: [ 4 12]
Elementi na pozicijama (1,2) i (1,3): [7 8]


In [28]:
M = np.arange(25).reshape(5, 5) + 1
print('Vrednosti od 3. do 4. elementa u nultom redu:', M[0,3:5])
print('Kvadratna podmatrica reda 2 u donjem desnom uglu:\n', M[-2:,-2:])
print('Elementi svakog drugog reda pocev od 2. i elementi svake druge kolone:\n', M[2::2,::2])
print('Elementi sa koordinatama (0,2), (1,3), (2,4):', M[(0,1,2),(2,3,4)])

Vrednosti od 3. do 4. elementa u nultom redu: [4 5]
Kvadratna podmatrica reda 2 u donjem desnom uglu:
 [[19 20]
 [24 25]]
Elementi svakog drugog reda pocev od 2. i elementi svake druge kolone:
 [[11 13 15]
 [21 23 25]]
Elementi sa koordinatama (0,2), (1,3), (2,4): [ 3  9 15]


In [29]:
M = np.arange(9).reshape(3, 3)
print('M =\n', M)
average = np.average(M)
print(np.sum(M[M > average]))


M =
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
26


In [31]:
n = 4
M = np.zeros((n,n))
for i in range(n):
    M[i][n-i-1] = i+1
print(M)

[[0. 0. 0. 1.]
 [0. 0. 2. 0.]
 [0. 3. 0. 0.]
 [4. 0. 0. 0.]]


In [32]:
from numpy import linalg as LA

In [36]:
A = np.array([[1, 2, 4], [-5, 7, 2], [5, 1, 9]])
print('Matrica:')
print(A)
print('Determinanta: ', LA.det(A))
print()
print('Inverz:')
print(LA.inv(A))
print()
l, x = LA.eig(A)
print('Sopstvene vrednosti date u nizu:', l)
print('Sopstveni vektori dati kao kolone matrice:')
print(x)

Matrica:
[[ 1  2  4]
 [-5  7  2]
 [ 5  1  9]]
Determinanta:  11.00000000000001

Inverz:
[[ 5.54545455 -1.27272727 -2.18181818]
 [ 5.         -1.         -2.        ]
 [-3.63636364  0.81818182  1.54545455]]

Sopstvene vrednosti date u nizu: [ 0.17157288  5.82842712 11.        ]
Sopstveni vektori dati kao kolone matrice:
[[ 6.57393413e-01 -6.10635274e-02  3.71390676e-01]
 [ 6.10673901e-01 -9.20292562e-01  6.19577306e-16]
 [-4.41487584e-01  3.86436083e-01  9.28476691e-01]]


In [37]:
l, x = LA.eig(np.diag([1, 3, 2, 4]))
print(l)
print(x)

[1. 3. 2. 4.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [39]:
norm1 = LA.norm(A, ord=1)
norm2 = LA.norm(A, ord=2)
normf = LA.norm(A, ord='fro')
norminf = LA.norm(A, ord = np.inf)

print('Matricna 1-norma:', norm1)
print('Matricna 2-norma:', norm2)
print('Frobeniusova norma:', normf)
print('Matricna beskonacna norma:', norminf)

Matricna 1-norma: 15.0
Matricna 2-norma: 11.21324242009752
Frobeniusova norma: 14.352700094407323
Matricna beskonacna norma: 15.0


In [40]:
print('Kondicioni broj:', LA.cond(A))
# podrazumevano se koristi matricna 2-norma
LA.norm(A, ord = 2) * LA.norm(LA.inv(A), ord = 2)

Kondicioni broj: 102.39895228883015


102.39895228883077

In [42]:
b = np.array([1, 1]).T
delta = np.array([0.01, -0.01]).T

# matrica sa velikim kondicionim brojem
A1 = np.array([[1000, 1000], [1000, 999.99]])
print(LA.cond(A1))

# matrica sa malim kondicionim brojem
A2 = np.array([[1000, 1000], [1000, 0.01]])
print(LA.cond(A2))

# A1 * x = b i A1 * x = b + delta
print(LA.inv(A1).dot(b))
print(LA.inv(A1).dot(b + delta))

# A2 * x = b i A2 * x = b + delta
print(LA.inv(A2).dot(b))
print(LA.inv(A2).dot(b + delta))

399998.0000107766
2.6180691137495264
[0.001 0.   ]
[-1.99899  2.     ]
[0.001 0.   ]
[9.899998e-04 2.000020e-05]
